### ISSUE TITLE
Error in fredqd() while retrieving the dataset using the current civ file

### ISSUE THREAD

**Issue by szlatanos** [cykbennie/fbi#3]
To replicate:

`fl <- "https://files.stlouisfed.org/files/htdocs/fred-md/quarterly/current.csv"
df <- fredqd(file = fl, transform = TRUE)
`

It returns the following error:
> Error in 1:ind_notna : result would be too long a vector                             
> In addition: Warning message:
> In min(which(is.na(rawdata[, 1]))) :
>   no non-missing arguments to min; returning Inf

**Comment by cykbennie** [comment]
Fixed the issue on Jan 27, 2023.
